(cl:in-package tm_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TIME-VAL
          TIME
          CONTROLLER_TIME-VAL
          CONTROLLER_TIME
          Q_COMMAND-VAL
          Q_COMMAND
          QD_COMMAND-VAL
          QD_COMMAND
          QT_COMMAND-VAL
          QT_COMMAND
          Q_ACTUAL-VAL
          Q_ACTUAL
          QD_ACTUAL-VAL
          QD_ACTUAL
          QT_ACTUAL-VAL
          QT_ACTUAL
          TOOL0_POS_COMMAND-VAL
          TOOL0_POS_COMMAND
          TOOL0_POS_ACTUAL-VAL
          TOOL0_POS_ACTUAL
          TOOL_POS_COMMAND-VAL
          TOOL_POS_COMMAND
          TOOL_POS_ACTUAL-VAL
          TOOL_POS_ACTUAL
          TCP_SPEED-VAL
          TCP_SPEED
          TCP_FORCE-VAL
          TCP_FORCE
          KINE_CONFIG-VAL
          KINE_CONFIG
          COMMON_SPEED_RATIO-VAL
          COMMON_SPEED_RATIO
          ROBOT_MODE-VAL
          ROBOT_MODE
          SAFETY_MODE-VAL
          SAFETY_MODE
          TEACH_MODE-VAL
          TEACH_MODE
          CONTROL_MODE-VAL
          CONTROL_MODE
          ERROR_CODE_0-VAL
          ERROR_CODE_0
          ERROR_CODE_1-VAL
          ERROR_CODE_1
))